---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anthill
spec:
  replicas: 1
  selector:
    matchLabels:
      name: anthill
  template:
    metadata:
      labels:
        name: anthill
    spec:
      serviceAccountName: anthill
      containers:
        - name: anthill
          # Replace this with the built image name
          image: REPLACE_IMAGE
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - anthill
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "anthill"
